name=dataCodec
version=0.1.0
author=Kio (Kanata Hagiwara)
maintainer=Kio (Kanata Hagiwara) <domka.mechanic@gmail.com>
sentence=Library for encoding and decoding data for communication.
category=Uncategorized
url=https://github.com/KARURA-project/dataCodec/
architectures=*