[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "data_codec"
version = "0.0.0"
description = "Library for encoding and decoding data for communication."
authors = [
    {name = "Kio (Kanata Hagiwara)", email = "domka.mechanic@gmail.com"}
]

[tool.setuptools]
packages = ["data_codec"]